#title: 'prototowb.github.io'
#description: "Personal Repo Site"
#baseurl: "/prototowb.github.io"
#url: "https://prototowb.github.io"

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'Join the <a href="https://discord.gg/PrzPKmd">Discord</a> | follow me on <a href="https://twitter.com/prototowb">twitter</a>'

#style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

#markdown: kramdown

#plugins:
#  - jekyll-seo-tag
